CREATE TABLE [dbo].[Users]
(
	[Id] INT NOT NULL PRIMARY KEY IDENTITY, 
    [TASKNAME] NCHAR(40) NULL, 
    [TASKDESC] NCHAR(100) NULL, 
    [COMPANY] NCHAR(100) NULL, 
    [CNAME] NCHAR(40) NULL,
    [CONTACT] NCHAR(40) NULL, 
    [EMAIL] NCHAR(40) NULL
)