CREATE TABLE [dbo].[Table]
(
	[Id] INT NOT NULL PRIMARY KEY IDENTITY, 
    [USERNAME] NCHAR(40) NULL, 
    [PASSWORD] NCHAR(40) NULL, 
    [EMAIL] NCHAR(100) NULL, 
    [FIRSTNAME] NCHAR(40) NULL, 
    [LASTNAME] NCHAR(40) NULL
)
