CREATE TABLE [dbo].[Users]
(
	[Id] INT NOT NULL PRIMARY KEY IDENTITY, 
    [USERNAME] NCHAR(40) NULL, 
    [PASSWORD] NCHAR(40) NULL, 
    [EMAIL] NCHAR(100) NULL, 
    [FIRSTNAME] NCHAR(40) NULL, 
    [LASTNAME] NCHAR(40) NULL,
    [ROLE] INT(1) NULL,
    [LOGGEDIN] INT NULL
)
